version: '2'
services:
  db:
    image: db
    build: ./test-database
    container_name: db
    expose:
    - "3306"
    ports:
    - "6002:3306"
    healthcheck:
        test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
        timeout: 20s
        retries: 10
  users-service:
    restart: always
    depends_on:
      db:
        condition: service_healthy
    build: ./users-service
    image: users-service
    container_name: users-service
    ports:
     - "6001:6001"
    links:
    - db:db
    environment:
     - DATABASE_HOST=db
